# Generated by Django 3.1 on 2020-09-17 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auctions',
            new_name='Auction',
        ),
    ]
